### ISSUE TITLE
OSError: Failed to load library

### ISSUE THREAD

**Issue by justintiger** [daniegr/EfficientPose#33]
Does someone know whats the problem? 

Traceback (most recent call last):
  File "track.py", line 589, in <module>
    main(file_path=file_path, model_name=model_name, framework_name=framework_name, visualize=visualize, store=store)
  File "track.py", line 538, in main
    elif 'Video' in [track.track_type for track in MediaInfo.parse(file_path).tracks]:
  File "/home/ihomelab/anaconda3/envs/efficientpose/lib/python3.6/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/ihomelab/anaconda3/envs/efficientpose/lib/python3.6/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")

**Comment by daniegr** [comment]
@justintiger: Which OS are you operating on? I suspect this is an issue related to Ubuntu: [https://github.com/sbraz/pymediainfo/issues/109](https://github.com/sbraz/pymediainfo/issues/109). As a solution for now, I would suggest you to install a previous version of pymediainfo, such as 4.1.

**Comment by A7777-gp** [comment]
Hello author, I also encountered this error, I was in Ubuntu18.04, graphics card 3080, CUDA11.1 to running.For PyMdiainfo, I tried 5.0.3 and 4.1 and both reported errors.How to solve this problem? Thanks！
